version: "3.8"

x-logging: &default-logging
  driver: json-file
  options:
    max-size: "100m"
    max-file: "100"

networks:
  common-net: {}

services:
  postgres_db:
    container_name: portfolio_db
    image: bitnami/postgresql:latest
    platform: linux/amd64
    ports:
      - ${POSTGRESQL_PORT}:5432
    restart: always
    volumes:
      - db-data:/bitnami/postgresql
      - ./database:/docker-entrypoint-initdb.d
    environment:
      - POSTGRESQL_DATABASE=${POSTGRESQL_DATABASE}
      - POSTGRESQL_USERNAME=${POSTGRESQL_USERNAME}
      - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}
      - POSTGRESQL_LOGGING_COLLECTOR=true
      - POSTGRESQL_LOG_MIN_ERROR_STATEMENT=error
      - POSTGRESQL_LOG_STATEMENTS=all
    logging: *default-logging

  frontend:
    build:
      context: ./fe
    ports:
      - "3000:3000"
    volumes:
      - ./fe:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=${VITE_API_URL}
    command: npm run dev
    depends_on:
      - backend

  backend:
    build:
      context: ./be
    ports:
      - "5000:5000"
    volumes:
      - ./be:/app
      - /app/node_modules
    command: npm run start:dev
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
    depends_on:
      - postgres_db

volumes:
  db-data:
