version: '3.8'

x-logging: &default-logging
  driver: json-file
  options:
    max-size: "100m"
    max-file: "100"

networks:
  docker-network:
    driver: bridge

services:
  postgres_db:
    container_name: portfolio_db
    image: bitnami/postgresql:latest
    platform: linux/amd64
    ports:
      - ${POSTGRESQL_PORT}:5432
    restart: always
    volumes:
      - db-data:/bitnami/postgresql
      - ./database/init:/docker-entrypoint-initdb.d
    environment:
      - POSTGRESQL_DATABASE=${POSTGRESQL_DATABASE}
      - POSTGRESQL_USERNAME=${POSTGRESQL_USERNAME}
      - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}
      - POSTGRESQL_LOGGING_COLLECTOR=true  
      - POSTGRESQL_LOG_MIN_ERROR_STATEMENT=error  
      - POSTGRESQL_LOG_STATEMENTS=all  
    networks:
      - docker-network
    logging: *default-logging

volumes:
  db-data:
